### ISSUE TITLE
MCHyper format guide.

### ISSUE THREAD

**Issue by DonCyriac** [reactive-systems/MCHyper#1]
Is there a guide I can follow to write formulas in the MCHyper format?

**Comment by NorineCoenen** [comment]
Hi, 
there is no such guide, but you can find the grammar in [this file](https://github.com/reactive-systems/MCHyper/blob/90c489b3c9152ac8e79713197fd8f39c021490c0/src/Logic.hs#L34) and check out our case studies for examples, e.g. [here](https://github.com/reactive-systems/MCHyper/blob/master/case-studies/alternation-free_2015/8b10b/formulas.txt). 
In general, formulas in the MCHyper format use the Polish notation and are fully bracketed. De Bruijn indices are used to link atomic propositions to trace quantifiers and the AP names need to be escaped when calling MCHyper from the terminal. For example, the HyperLTL formula `forall pi. forall pi'. a_pi -> b_pi'` is written as `Forall (Forall (Implies (AP \"a\" 0) (AP \"b\" 1)))` in the MCHyper format.
